name: corekit
description: "An opinionated core for a basic project based on riverpod"
version: 0.0.18
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  animations: ^2.0.11
  basic_components:
    git:
      url: https://github.com/Order-of-Runes/basic_components.git
      ref: main
  better_components:
    git:
      url: https://github.com/Order-of-Runes/better_components.git
      ref: main
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  foundation:
    git:
      url: https://github.com/Order-of-Runes/foundation.git
      ref: main
  go_router: ^16.1.0
  rusty_dart:
    git:
      url: https://github.com/TheMakersPrime/rusty_dart.git
      ref: main
  sembast: ^3.8.1+1
  sembast_sqflite: ^2.2.0+4
  sherlog:
    git:
      url: https://github.com/TheMakersPrime/sherlog.git
      ref: main
  sqflite: ^2.4.1
  utils:
    git:
      url: https://github.com/Order-of-Runes/utils.git
      ref: main

dev_dependencies:
  very_good_analysis: ^7.0.0